version: '3'

services:

  frontend:
    volumes:
      - .:/opt/frontend
    environment:
      RAZZLE_API_PATH: "http://localhost:9085/Plone"
      RAZZLE_INTERNAL_API_PATH: "http://ploneapi:8080/Plone"
      PORT: "9000"
    ports:
    - "9000:9000"
    - "9001:9001"
    entrypoint: sh -c "tail -f /dev/null"

  ploneapi:
    entrypoint: sh -c "tail -f /dev/null"
    environment:
      CORS_ALLOW_ORIGIN: "http://localhost:9000"
    ports:
      - "9085:8080"
    volumes:
      - ./plone-src:/plone/instance/src
